name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main  # Set this to your default branch
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main  # Set this to your default branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Build and Deploy
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.x'  # Set this to your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Provided by GitHub
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          app_location: "/"  # App source code path
          api_location: ""  # API source code path - set this to the path of your API code if you have one
          output_location: "dist"  # Built artifacts folder - Vue CLI default build output is "dist"
          ###### End of Repository/Build Configurations ######

